version: '3.7'
services:
    vault:
        image: "vault:1.7.0"
        ports: 
            - "8200:8200"
        volumes:
            - ./auditLog:/vault/logs
            - ./fileStorage:/vault/file
        environment: 
            - VAULT_DEV_ROOT_TOKEN_ID=myroot
        cap_add:
            - IPC_LOCK
        networks:
            - vault

    rabbitmq:
        image: "rabbitmq:3.8.14-management"
        ports: 
            - '5672:5672'
            - '15672:15672'
        environment:
            AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
            RABBITMQ_DEFAULT_USER: 'admin'
            RABBITMQ_DEFAULT_PASS: 'admin'
        networks:
            - vault

networks:
    vault:
