version: '3.7'
services:
    vault:
        image: "vault:1.3.3"
        ports: 
            - "8200:8200"
        volumes:
            - ./auditLog:/vault/logs
            - ./fileStorage:/vault/file
        environment: 
            - VAULT_DEV_ROOT_TOKEN_ID=myroot
        cap_add:
            - IPC_LOCK
        networks:
            - vault

networks:
    vault:
